protected/modules/admin/models/Reports.php
<?php

/**
 * This is the model class for table "settings_postage".
 *
 * The followings are the available columns in table 'settings_postage':
 * 
 */
class Reports extends CFormModel
{
    /**
     * Returns the static model of the specified AR class.
     * @param string $className active record class name.
     * @return Postage the static model class
     */
    public static function model($className=__CLASS__) {
            return parent::model($className);
    }

	/**
	 * @return array validation rules for model attributes.
	 */
    public function rules() {
            // NOTE: you should only define rules for those attributes that
            // will receive user inputs.
            return array(
//                    array('name, cost', 'required'),
            );
    }

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
//			'id' => 'ID',
//			'name' => 'Name',
//			'cost' => 'Cost',
		);
	}
}

protected/modules/admin/controllers/ReportsController.php
<?php

class ReportsController extends Controller
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
//			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('index', 'view', 'useremail', 'userstatus', 'billing'),
				'roles'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Lists all models.
	 */
    public function actionIndex() {
            $this->render('index');
    }
    
    public function actionUseremail(){
        $model = new UseremailReports();
        if(isset($_GET['date_from']) && isset($_GET['date_to'])){
            $type = $_GET['type'];
            $customer_user_id = '';
            $for = $_GET['for'];
            if($for==UseremailReports::FORCUSTOMER){
                $customer_user_id = $_GET['customer'];
            } else if($for==UseremailReports::FORUSER){
                $customer_user_id = $_GET['user'];
            }
            $model->printReport(array('from'=>$_GET['date_from'], 'to'=>$_GET['date_to']), $type, $for, $customer_user_id);
        }
        
    }
    public function actionBilling(){
        $model = new BillingReports();
        if(isset($_GET['date_from']) && isset($_GET['date_to'])){
            $type = $_GET['type'];
            $model->printReport(array('from'=>$_GET['date_from'], 'to'=>$_GET['date_to']), $type);
        } else {
            echo "Invalid data submitted";
        }
//        $date = array('from'=> date('m/d/Y', time()), 'to'=>date('m/d/Y', time()+(7*24*60*60)));
//        $this->renderPartial('billing', array('date'=>$date));
    }
    public function actionUserstatus(){
        $model = new UserstatusReports;
        if(isset($_GET['type'])){
            $model->printReport($_GET['type']);
        } 
        else {
//            $this->renderPartial('userstatus', array('model'=>$model));
            echo "Invalid data submitted";
        }
    }

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Postage the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Reports::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Postage $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='postage-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/modules/admin/views/reports/billing.php
<?php
/* @var $this ReportsController
 * @var $model BillingReports
 * @var $form TbActiveForm
 **/
?>
<?php

$form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id'=>'billing-report-form',
    'enableAjaxValidation'=>true,
    'type'=>'horizontal',
));
?>

<?php $date = array('from'=> date('m/d/Y', time()-(7*24*60*60)), 'to'=>date('m/d/Y', time())); ?>
<div class="control-group ">
    <label for="Date_from" class="control-label">Start Date: </label>
    <div class="controls">
<?php $this->widget('zii.widgets.jui.CJuiDatePicker',array(
    'name'=>'Date[from]',
    // additional javascript options for the date picker plugin
    'options'=>array(
        'showAnim'=>'fold',
    ),
    'value'=>$date['from'],
    'htmlOptions'=>array(
		'id'=>'billing_date_from',
        'style'=>'height:20px;'
    ),
));
?>
    </div>
</div>

<div class="control-group ">
    <label for="Date_to" class="control-label">End Date: </label>
    <div class="controls">
<?php
$this->widget('zii.widgets.jui.CJuiDatePicker',array(
    'name'=>'Date[to]',
    // additional javascript options for the date picker plugin
    'options'=>array(
        'showAnim'=>'fold',
    ),
    'value'=>$date['to'],
    'htmlOptions'=>array(
		'id'=>'billing_date_to',
        'style'=>'height:20px;'
    ),
));
?>
    </div>            
</div>

<?php echo $form->checkboxRow($model, 'type'); ?>

<div class="control-group ">
    <label class="control-label">&nbsp;</label>
    <div class="controls">
<?php $this->widget('bootstrap.widgets.TbButton', array('buttonType'=>'submit', 'type'=>'primary', 'label'=>'Show')); ?>
    </div>
</div>
<?php $this->endWidget(); ?>
<script type="text/javascript">
$('form#billing-report-form').on('submit', function(e){
    e.preventDefault();
    var from = new Date($('input#billing_date_from').val());
    var to = new Date($('input#billing_date_to').val());
    var date_from = from.valueOf()/1000;
    var date_to = to.valueOf()/1000;
    var type = $('#BillingReports_type:checked');
    if(type.length>0){
        type = type.val();
    } else {
        type = 0;
    }
    window.open('<?php echo $this->createAbsoluteUrl('reports/billing') ?>/date_from/'+date_from+"/date_to/"+date_to+'/type/'+type, 'Report', 'fullscreen=yes,width=600,height=400,scrollbars=yes');
});
</script>

protected/modules/admin/views/reports/index.php
<?php
/* @var $this PostageController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
    'Admin' => 'admin/index',
    'Reports',
);
?>
<h1>Reports</h1>

<?php
//$this->widget('zii.widgets.jui.CJuiTabs',array(
//    'tabs'=>array(
////        'User Email'=>array('id'=>'user-email', 'url'=>array('reports/useremail')),
//        'User Email'=>array('id'=>'user-email', 'content'=>$this->renderPartial('useremail', array('model'=>new UseremailReports), false, true)),
//        'Billing'=>array('id'=>'billing','content'=>'Billing Reports'),
//        'User States'=>array('id'=>'user-states', 'ajax'=>array('reports/userstatus')),
//    ),
//    // additional javascript options for the tabs plugin
//    'options'=>array(
//        'collapsible'=>true,
//    ),
//));


$this->widget('bootstrap.widgets.TbTabs', array(
    'type'=>'tabs', // 'tabs' or 'pills'
    'tabs'=>array(
        array('label'=>'User Email', 'content'=>$this->renderPartial('useremail', array('model'=>new UseremailReports()), true), 'active'=>true),
        array('label'=>'Billing', 'content'=>$this->renderPartial('billing', array('model'=>new BillingReports()), true), 'active'=>false),
        array('label'=>'User Status', 'content'=>$this->renderPartial('userstatus', array('model'=>new UserstatusReports()), true), 'active'=>false),
    ),
));

//$this->widget('bootstrap.widgets.TbMenu', array(
//    'type'=>'tabs', // '', 'tabs', 'pills' (or 'list')
//    'stacked'=>false, // whether this is a stacked menu
//    'items'=>array(
//        array('label'=>'User Email', 'url'=>'#', 'active'=>true),
//        array('label'=>'Billing', 'url'=>'#'),
//        array('label'=>'User Status', 'url'=>'#'),
//    ),
//));
?>

protected/modules/admin/views/reports/useremail.php
<?php
/* @var $this ReprotsController */
/* @var $form TbActiveForm */
/* @var $model UseremailReports */
$form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id'=>'useremail-report-form',
    'enableAjaxValidation'=>true,
    'type'=>'horizontal',
));
//$form->radio($model, 'for');
?>
<div id="report-for-container">
<?php echo $form->radioButtonListRow($model, 'for', $model->getForTypes()); ?>
</div>
<div id="report-customerdropdown-container" style="display:none;" class="dropdowns-container">
<?php
 echo $form->dropDownListRow($model, 'customer', CHtml::listData($model->getCustomers(), 'id', 'name')); ?>
</div>
<div id="report-userdropdown-container" style="display:none;" class="dropdowns-container">
<?php echo $form->dropDownListRow($model, 'user', CHtml::listData($model->getUserList(), 'id', 'name')); ?>
</div>
<div id="report-type-container">
    <div class="control-group ">
<?php echo $form->radioButtonListRow($model, 'type', $model->getTypes(), array('class'=>'report_type_checkbox')); ?>
    </div>
</div>
<div id="report-dates-container">
<?php $date = array('from'=> date('m/d/Y', time()-(7*24*60*60)), 'to'=>date('m/d/Y', time())); ?>
<div class="control-group ">
    <label for="Date_from" class="control-label">Start Date: </label>
    <div class="controls">
<?php $this->widget('zii.widgets.jui.CJuiDatePicker',array(
    'name'=>'Date[from]',
    // additional javascript options for the date picker plugin
    'options'=>array(
        'showAnim'=>'fold',
    ),
    'value'=>$date['from'],
    'htmlOptions'=>array(
        'style'=>'height:20px;'
    ),
));
?>
    </div>
</div>

<div class="control-group ">
    <label for="Date_to" class="control-label">End Date: </label>
    <div class="controls">
<?php
$this->widget('zii.widgets.jui.CJuiDatePicker',array(
    'name'=>'Date[to]',
    // additional javascript options for the date picker plugin
    'options'=>array(
        'showAnim'=>'fold',
    ),
    'value'=>$date['to'],
    'htmlOptions'=>array(
        'style'=>'height:20px;'
    ),
));
?>
    </div>            
</div>
</div>
<div class="control-group ">
    <label class="control-label">&nbsp;</label>
    <div class="controls">
<?php $this->widget('bootstrap.widgets.TbButton', array('buttonType'=>'submit', 'type'=>'primary', 'label'=>'Show')); ?>
    </div>
</div>
<?php $this->endWidget(); ?>
<script type="text/javascript">
$('#UseremailReports_for_1').on('click', function(e){
    if($(this).is(':checked')){
        $('.dropdowns-container').hide();
        $('#report-customerdropdown-container').show();
    }
});

$('#UseremailReports_for_2').on('click', function(e){
    if($(this).is(':checked')){
        $('.dropdowns-container').hide();
        $('#report-userdropdown-container').show();
    }
});
$('#UseremailReports_for_0').on('click', function(e){
    if($(this).is(':checked')){
        $('.dropdowns-container').hide();
    }
});

$('form#useremail-report-form').on('submit', function(e){
    e.preventDefault();
    if($('.report_type_checkbox:checked').length>0){
        var from = new Date($('input#Date_from').val());
        var to = new Date($('input#Date_to').val());
        var date_from = from.valueOf()/1000;
        var date_to = to.valueOf()/1000;
        
        var type_array = [];
        $.each($('.report_type_checkbox:checked'), function(i,v){
            type_array[i] = v.value;
        });
        var report_for = $("input[name='UseremailReports[for]']:checked").val();
        var customer_or_user = '';
        if($('#report-userdropdown-container').css('display')!='none'){
            var user = $("select[name='UseremailReports[user]']").val();
            customer_or_user = '/user/'+user;
        }
        if($('#report-customerdropdown-container').css('display')!='none'){
            var customer = $("select[name='UseremailReports[customer]']").val();
            customer_or_user = '/customer/'+customer;
        }
        var type=type_array.join('-');        
        var report_url = '<?php echo $this->createAbsoluteUrl('reports/useremail') ?>/date_from/'+date_from+"/date_to/"+date_to+'/type/'+type+'/for/'+report_for+customer_or_user;
        window.open(report_url, 'Report', 'fullscreen=yes,width=600,height=400,scrollbars=yes');
    } else {
        alert('Please select one or more report type(s)');
    }
});
</script>

protected/modules/admin/views/reports/userstatus.php
<?php
/* @var $this ReportsController */
/* @var $form TbActiveForm */
/* @var $model UserstatusReports */
$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id'=>'userstatus-report-form',
    'type'=>'horizontal',
    'action'=> $this->createUrl('reports/userstatus'),
));
//echo '<form action="userstatus-report-form" class="form-horizontal" method="post" action="'.$this->createUrl('reports/userstatus').'">';
//$form->radio($model, 'for');
echo $form->checkboxList($model, 'type', $model->getTypes(), array('class'=>'report-type'));
$this->widget('bootstrap.widgets.TbButton', array('buttonType'=>'submit', 'type'=>'primary', 'label'=>'Show'));
//echo '<form>';
$this->endWidget();
?>
<script type="text/javascript">
$('form#userstatus-report-form').on('submit', function(e){
    e.preventDefault();
    var checkboxes = $('input.report-type:checked');
    if(checkboxes.length<1){
        alert('Please select report type.');
    } else {
        var type=0;
        $.each(checkboxes, function(i,v){
            type += parseInt(v.value);
        });
        window.open('<?php echo $this->createAbsoluteUrl('reports/userstatus') ?>/type/'+type, 'Report', 'fullscreen=yes,width=600,height=400,scrollbars=yes');
    }
});
</script>